repos:
  - swift-sdk
  - ofrep-swift-client-provider

emeritus:
  - alina-v1
  - Calibretto

triagers:
  - cupofcat

approvers: []

maintainers:
  - fabriziodemaria
  - mfranberg
  - toddbaert
  - nicklasl
  - nickybondarenko
  - vahidlazio

admins: []
