repos:
  - java-sdk
  - java-sdk-contrib

emeritus:
  - ajhelsby
  - agentgonzo
  - Kavindu-Dodan
  - thiyagu06

triagers:
  - cupofcat

approvers:
  - guidobrei
  - thomaspoignant
  - thisthat
  - liran2000

maintainers:
  - aepfli
  - justinabrahms
  - toddbaert
  - chrfwow

admins: []
