repos:
  - java-sdk
  - java-sdk-contrib

approvers:
  - thiyagu06
  - thomaspoignant
  - ajhelsby
  - thisthat
  - liran2000

maintainers:
  - aepfli
  - justinabrahms
  - toddbaert
  - agentgonzo
  - kavindu-dodan
  - chrfwow

admins: []
