# org settings
name: OpenFeature
description: Standardizing Feature Flagging for Everyone

default_repository_permission: read

has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false

admins:
  # org management bot
  - openfeaturebot

  # governance board
  - beeme1mr
  - AloisReitbauer
  - moredip
  - dabeeeenster
  - jrydberg
  - jonathannorris
  - weyert

  # technical steering committee
  - lukas-reining
  - kinyoklion
  - toddbaert
  - thomaspoignant

# org member settings - keep alphabetical
# add yourself here if you're interested in being an org member!
members:
  - ABC2015
  - adams85
  - aepfli
  - agardnerIT
  - agentgonzo
  - ajhelsby
  - ajwootto
  - alemrtv
  - alexandraoberaigner
  - AlexsJones
  - alina-v1
  - alxckn
  - andrewdmaclean
  - AnaisUrlichs
  - anghelflorinm
  - Arhell
  - ARobertsCollibra
  - arttonoyan
  - askpt
  - austindrenski
  - bacherfl
  - benjiro
  - Billlynch
  - c4milo
  - Calibretto
  - cdonnellytx
  - chrfwow
  - colebaileygit
  - craigpastro
  - cpitstick-latai
  - davejohnston
  - DavidPHirsch
  - DBlanchard88
  - dgorton
  - djosephsen
  - dlopes7
  - dnsmichi
  - dominikhaska
  - dyladan
  - ejscunha
  - ericpattison
  - fabriziodemaria
  - faulkt
  - federicobond
  - gagantrivedi
  - gruebel
  - guidobrei
  - hairyhenderson
  - heckelmann
  - hlipsig
  - InTheCloudDan
  - ivarconr
  - jakedoublev
  - james-milligan
  - jamescarr
  - jarebudev
  - jbovet
  - jenshenneberg 
  - josecolella
  - juanparadox
  - justaugustus
  - justinabrahms
  - kamil-nowosad
  - Kavindu-Dodan
  - kbychu
  - laliconfigcat
  - liran2000
  - lopitz
  - luizbon
  - luizgribeiro
  - madhead
  - markphelps
  - matthewelwell
  - maxveldink
  - mfranberg
  - mihirm21
  - miigwi
  - mkorbi
  - mowies
  - mschoenlaub
  - nicklasl
  - nickybondarenko
  - nikolasleblanc
  - odubajDT
  - oleg-nenashev
  - Olunusib
  - oxddr
  - patricioe
  - pradeepbbl
  - rcrowe
  - RealAnna
  - rgrassian-split
  - rschosser
  - ryanprayogo
  - s-sen
  - sago2k8
  - salaboy
  - sheepduke
  - sighphyre
  - sindhuinti
  - skyerus
  - ssharaev
  - staceypotter
  - tcarrio
  - technicalpickles
  - tegenterter
  - therealmitchconnors
  - thisthat
  - thiyagu06
  - thschue
  - tjosepo
  - tomkerkhove
  - UtkarshSharma2612
  - vahidlazio
  - vpetrusevici
  - warber
  - wichopy
  - znonthedev
  - z4kn4fein

teams:
  emeritus:
    members:
      - oleg-nenashev
      - thschue

  admins:
    members: []

  maintainers:
    members: []

  approvers:
    members: []

  Technical Steering Committee:
    members:
      - lukas-reining
      - kinyoklion
      - toddbaert
      - thomaspoignant

  Governance Board:
    members:
      - beeme1mr
      - AloisReitbauer
      - AlexsJones
      - moredip
      - justinabrahms
      - dabeeeenster

  Interested Parties:
    description: Group for members of https://github.com/openfeatureflags/governance/blob/main/interested-parties.md
    maintainers:
      - justinabrahms
      - AloisReitbauer
      - beeme1mr

    members:
      - miigwi
      - weyert
      - dabeeeenster
      - markphelps
      - salaboy
      - dnsmichi
      - justaugustus
      - therealmitchconnors
      - davejohnston
      - AlexsJones
      - dyladan
      - benjiro
      - tomkerkhove
      - kinyoklion
      - mkorbi
      - thomaspoignant
      - faulkt
      - tegenterter
      - AnaisUrlichs
      - thschue
      - james-milligan
    privacy: closed
    repos:
      vendor-survey: write

repos:
  # Template for adding a new project
  # mandatory:
  #
  # <name>:
  #   description: <description>
  #
  # optional:
  #   archived: <true|false> - defaults to false
  #   private: <true|false> - defaults to false
  #   has_issues: <true|false> - defaults to true
  #   has_projects: <true|false> - defaults to true
  #   has_wiki: <true|false> - defaults to false
  .github:
    description: This repository stores various defaults for the GitHub organization
  angular-test-app:
  cli:
    description: OpenFeatureâ€™s official command-line tool
  cloud-native-demo:
    description: A cloud-native feature flag demo, featuring multiple providers, telemetry, and a guided tour
  community:
    description: OpenFeature project community and governance
  community-tooling:
    description: Tools for Community Management
  contribfest-eu-24:
  dart-server-sdk:
  demo-repository:
    description: A code repository designed to show the best GitHub has to offer.
    private: true
  docs.openfeature.dev:
    description: OpenFeature Documentation
    has_projects: false
    archived: true
  dotnet-sdk:
    description: .NET implementation of the OpenFeature SDK
  dotnet-sdk-contrib:
    description: OpenFeature Providers and Hooks for .NET
  elixir-sdk:
    description: Elixir SDK for OpenFeature
  five-minutes-to-feature-flags:
    description: A short introduction to the core concepts of OpenFeature
  flagd:
    description: A feature flag daemon with a Unix philosophy
  flagd-testbed:
    description: Shared test harness for flagd SDK testing, with Gherkin tests
  flagd-schemas:
    description: Schemas and spec files pertaining to flagd
    homepage: https://buf.build/open-feature/flagd
  go-sdk:
    description: Go SDK for OpenFeature
  go-sdk-contrib:
    description: Community maintained OpenFeature Providers and Hooks for Go
  homebrew-core:
    description: "\U0001F37B Default formulae for the missing package manager
      for macOS (or Linux)"
    has_issues: false
    homepage: https://brew.sh
  java-sdk:
    description: Java implementation of the OpenFeature SDK
  java-sdk-contrib:
    description: Community contributions for hooks and reference providers
  js-sdk:
    description: JavaScript SDK for OpenFeature
  js-sdk-contrib:
    description: OpenFeature Providers and Hooks for JavaScript
  killercoda:
    description: Killercoda Interactive Examples for OpenFeature
    has_projects: false
  kotlin-sdk:
    description: Kotlin implementation of the OpenFeature SDK for Android clients
  ofep:
    description: A focal point for OpenFeature research, proposals and requests
      for comments
    has_projects: false
  open-feature-operator:
    description: A Kubernetes feature flag operator
  open-feature.github.io:
    archived: true
    description: OpenFeature website
  openfeature.dev:
    description: OpenFeature Website
  php-sdk:
    description: PHP implementation of the OpenFeature SDK
    has_projects: false
  php-sdk-contrib:
    description: OpenFeature Providers and Hooks for PHP
  php-sdk-contrib-flagd-provider:
    description: Flagd provider for the OpenFeature PHP SDK
    private: true
  playground:
    description: OpenFeature SDK demos and experimentation
  protocol:
    description: OpenFeature Remote Evaluation Protocol
  python-sdk:
    description: Python SDK for OpenFeature
  python-sdk-contrib:
    description: Community contributions for hooks and reference providers in
      python
  ruby-sdk:
    description: Ruby implementation of the OpenFeature SDK
  react-native-test-app:
  react-test-app:
    description: Small test app for @openfeature/react-sdk development and e2e testing
  ruby-sdk:
    description: Ruby implementation of the OpenFeature SDK
  ruby-sdk-contrib:
    description: Community contributions for hooks and reference providers in Ruby
  rust-sdk:
  rust-sdk-contrib:
    description: Community maintained OpenFeature Providers and Hooks for Rust
  spec:
    description: OpenFeature specification
  swift-sdk:
    description: Swift implementation of the OpenFeature SDK for iOS clients
  toc-proposal:
    description: TOC proposal fork
  toggle-shop:
    description: ToggleShop is a demo e-commerce app for showcasing OpenFeature
  vendor-survey:
    archived: true
    private: true
  watchman:
    description: A Kubernetes admission controller driven by open-feature
