repos:
  - dotnet-sdk
  - dotnet-sdk-contrib

emeritus:
  - austindrenski
  - cdonnellytx
  - jenshenneberg
  - bacherfl

triagers:
  - cupofcat

approvers:
  - arttonoyan
  - chrfwow

maintainers:
  - beeme1mr
  - toddbaert
  - benjiro
  - kinyoklion
  - askpt
  - kylejuliandev

admins: []
