repos:
  - ofep
  - community
  - community-tooling
  - .github
  - spec
  - toc-proposal

approvers:
- AlexsJones
- AloisReitbauer
- InTheCloudDan
- Kavindu-Dodan
- aepfli
- agentgonzo
- bacherfl
- beeme1mr
- benjiro
- dabeeeenster
- davejohnston
- fabriziodemaria
- federicobond
- james-milligan
- josecolella
- justinabrahms
- kinyoklion
- lukas-reining
- moredip
- staceypotter
- tcarrio
- thiyagu06
- thomaspoignant
- toddbaert
- weyert

maintainers:
  - DavidPHirsch

admins: []
