repos:
  - ofep
  - community
  - .github
  - spec

approvers:
  - DavidPHirsch
  - beeme1mr
  - AloisReitbauer
  - AlexsJones
  - moredip
  - justinabrahms
  - dabeeeenster
  - agentgonzo
  - toddbaert
  - InTheCloudDan
  - benjiro
  - kinyoklion

maintainers: []

admins: []
