repos:
  - ofep
  - community
  - community-tooling
  - .github
  - spec
  - toc-proposal

emeritus:
  - Kavindu-Dodan

# keep alphabetical
approvers:
  - aepfli
  - agentgonzo
  - alexandraoberaigner
  - AlexsJones
  - AloisReitbauer
  - bacherfl
  - beeme1mr
  - benjiro
  - dabeeeenster
  - davejohnston
  - fabriziodemaria
  - federicobond
  - InTheCloudDan
  - james-milligan
  - jonathannorris
  - josecolella
  - jrydberg
  - justinabrahms
  - kinyoklion
  - lukas-reining
  - maxveldink
  - moredip
  - nicklasl
  - staceypotter
  - tcarrio
  - thiyagu06
  - thomaspoignant
  - toddbaert
  - weyert

maintainers:
  - DavidPHirsch

admins: []
