repos:
  - python-sdk
  - python-sdk-contrib

emeritus:
  - ajhelsby
  - hlipsig

triagers:
  - cupofcat

approvers: []

maintainers:
  - federicobond
  - dabeeeenster
  - mschoenlaub
  - tcarrio
  - matthewelwell
  - gruebel

admins: []
