repos:
  - flagd
  - flagd-schemas
  - flagd-testbed
  - open-feature-operator

emeritus:
  - AlexsJones
  - kavindu-dodan
  - odubajDT
  - skyerus

approvers:
  - aepfli
  - agardnerIT
  - alexandraoberaigner
  - beeme1mr
  - cupofcat
  - craigpastro
  - justinabrahms
  - tangenti
  - tcarrio
  - thisthat
  - thomaspoignant

maintainers:
  - bacherfl
  - james-milligan
  - toddbaert
  - lukas-reining

admins: []
