repos:
  - flagd
  - flagd-schemas
  - flagd-testbed
  - open-feature-operator

approvers:
  - agardnerIT
  - beeme1mr
  - craigpastro
  - justinabrahms
  - odubajDT
  - tcarrio
  - thisthat
  - thomaspoignant
 

maintainers:
  - AlexsJones
  - bacherfl
  - james-milligan
  - toddbaert
  - kavindu-dodan
  - skyerus

admins: []
