repos:
  - flagd
  - schemas
  - open-feature-operator

approvers:
  - thomaspoignant
  - justinabrahms
  - thisthat
  - tcarrio
  - beeme1mr
  - bacherfl
  - odubajDT
  - agardnerIT

maintainers:
  - AlexsJones
  - james-milligan
  - toddbaert
  - kavindu-dodan
  - skyerus

admins: []
