repos:
  - js-sdk
  - js-sdk-contrib
  - react-test-app

emeritus: []

triagers:
  - cupofcat

approvers:
  - aepfli
  - weyert
  - james-milligan
  - tcarrio
  - luizgribeiro
  - jonathannorris

maintainers:
  - beeme1mr
  - toddbaert
  - lukas-reining

admins: []
