repos:
  - protocol

emeritus:
  - Kavindu-Dodan
  - oxddr

approvers:

maintainers:
  - thomaspoignant
  - toddbaert
  - fabriziodemaria
  - nicklasl
  - kamil-nowosad
  - jonathannorris
  - lukas-reining

admins: []
