repos:
  - kotlin-sdk
  - kotlin-sdk-contrib

emeritus: []

triagers:
  - cupofcat

approvers: 
  - bencehornak
  
maintainers:
  - fabriziodemaria
  - nicklasl
  - nickybondarenko
  - toddbaert
  - vahidlazio

admins: []
