repos:
  - go-sdk
  - go-sdk-contrib

emeritus:
  - agentgonzo
  - AlexsJones
  - bacherfl
  - davejohnston
  - skyerus

triagers:
  - cupofcat

approvers:
  - bbland1
  - beeme1mr
  - erka
  - thisthat

maintainers:
  - james-milligan
  - Kavindu-Dodan
  - sahidvelji
  - thomaspoignant
  - toddbaert

admins: []
