
name: Organization Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'tools/**'
      - 'config/**'
  schedule:
    - cron: "0 0 * * *"

env:
  PERIBOLOS_ARGS: "--fix-org --fix-org-members --fix-repos --fix-team-members --fix-teams --min-admins=2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generating Peribolos configuration
        run: cd tools && go run peribolosbuilder.go -config=../config > ../peribolos.yaml && cd ..

      - name: Printing configuration for safety
        run: cat peribolos.yaml

      - name: Preparing credentials
        run: echo ${{ secrets.PERIBOLOS_GH_TOKEN }} >> github-token # a secret with the user token to be used for execution

      - name: Run Peribolos Configuration Verification
        if: github.event_name == 'pull_request'
        uses: docker://ghcr.io/dynatrace-innovationlab/peribolos:v0
        with:
          args: ${{ env.PERIBOLOS_ARGS }} --github-token-path github-token --config-path peribolos.yaml

      - name: Apply Peribolos Configuration
        if: github.event_name != 'pull_request'
        uses: docker://ghcr.io/dynatrace-innovationlab/peribolos:v0
        with:
          args: ${{ env.PERIBOLOS_ARGS }} --github-token-path github-token --config-path peribolos.yaml --confirm
